{
    "componentChunkName": "component---src-templates-concept-js",
    "path": "/concepts/exception/JavaScript/",
    "result": {"data":{"concept":{"slug":"concepts/Exception","frontmatter":{"wikipedia":"Exception_handling","shortDescription":"The representation of an unexpected situation that affects control flow.","relatedConcepts":["Object","ControlFlow","Return"],"text":[{"id":"tapl","sections":["14"]}]}},"misconceptions":{"totalCount":9,"edges":[{"node":{"fields":{"slug":"/misconceptions/Java/AnyClassException/","name":"AnyClassException","pl":"Java"},"frontmatter":{"shortDescription":"Any class can be an exception class"}}},{"node":{"fields":{"slug":"/misconceptions/Java/CatchAlwaysExecutes/","name":"CatchAlwaysExecutes","pl":"Java"},"frontmatter":{"shortDescription":"Catch blocks always get executed"}}},{"node":{"fields":{"slug":"/misconceptions/Java/CatchProvidesOptions/","name":"CatchProvidesOptions","pl":"Java"},"frontmatter":{"shortDescription":"Only the part of a catch block necessary to fix the cause of an exception is executed"}}},{"node":{"fields":{"slug":"/misconceptions/Java/ExceptionRoot/","name":"ExceptionRoot","pl":"Java"},"frontmatter":{"shortDescription":"Exception is the top-most exception class"}}},{"node":{"fields":{"slug":"/misconceptions/Java/NullPointerExceptionCompileTime/","name":"NullPointerExceptionCompileTime","pl":"Java"},"frontmatter":{"shortDescription":"NullPointerExceptions are detected at compile time"}}},{"node":{"fields":{"slug":"/misconceptions/Java/RuntimeExceptionChecked/","name":"RuntimeExceptionChecked","pl":"Java"},"frontmatter":{"shortDescription":"RuntimeExceptions are checked exceptions"}}},{"node":{"fields":{"slug":"/misconceptions/Java/TryCatchMandatory/","name":"TryCatchMandatory","pl":"Java"},"frontmatter":{"shortDescription":"When a piece of code can throw an exception, it must be surrounded with a try/catch block"}}},{"node":{"fields":{"slug":"/misconceptions/Java/TryFinishes/","name":"TryFinishes","pl":"Java"},"frontmatter":{"shortDescription":"Exceptions get thrown at the end of the try block"}}},{"node":{"fields":{"slug":"/misconceptions/JavaScript/AccessingInexistentPropertyError/","name":"AccessingInexistentPropertyError","pl":"JavaScript"},"frontmatter":{"shortDescription":"Accessing a non existent property on an object produces an error"}}}]},"pls":{"edges":[{"node":{"frontmatter":{"id":"Java"}}},{"node":{"frontmatter":{"id":"JavaScript"}}},{"node":{"frontmatter":{"id":"Python"}}},{"node":{"frontmatter":{"id":"Scratch"}}}]},"textbooks":{"nodes":[{"frontmatter":{"title":"Category Theory for Programmers","home":"https://github.com/hmemcpy/milewski-ctfp-pdf","author":"Bartosz Milewski"},"parent":{"name":"ctp"}},{"frontmatter":{"title":"Compilers: Principles, Techniques, and Tools","home":"https://suif.stanford.edu/dragonbook/","author":"Alfred Aho, Ravi Sethi, Jeffrey Ullman, Monica S. Lam"},"parent":{"name":"dragon"}},{"frontmatter":{"title":"nLab","home":"https://ncatlab.org/nlab/show/HomePage","author":"David Corfield, David Roberts, Mike Shulman, Toby Bartels, Todd Trimble"},"parent":{"name":"nlab"}},{"frontmatter":{"title":"Objects-First with Java","home":"https://www.bluej.org/objects-first/","author":"David J. Barnes & Michael Kölling"},"parent":{"name":"ofj6"}},{"frontmatter":{"title":"Sprechen Sie Java","home":"https://ssw.jku.at/Misc/JavaBuch/","author":"Hanspeter Mössenböck"},"parent":{"name":"ssj4"}},{"frontmatter":{"title":"Types and Programming Languages","home":"https://www.cis.upenn.edu/~bcpierce/tapl/","author":"Benjamin C. Pierce"},"parent":{"name":"tapl"}}]}},"pageContext":{"concept":"Exception","slug":"concepts/Exception","wikipediaSummary":"","pl":"JavaScript"}},
    "staticQueryHashes": ["3649515864","4169798128"]}